### ISSUE TITLE
Yubikey type module

### ISSUE THREAD

**Issue by CorruptComputer** [FrameworkComputer/ExpansionCards#2]
Would it be possible to have a Yubikey-like module for this as well? 

I'm thinking something like this could be used to store LUKS encryption keys for the SSD as well as any SSH keys a user may have. 

Would make it convenient to keep in the laptop while you are using it, while not having the risk of damaging a USB port while walking about. Also as a security feature when away from the laptop, just take the module with you.

**Comment by drewwestrick** [comment]
This is probably totally possible. Nitrokey is mostly open source and the firmware for the MCU they use, the STM32F103, is the link below. You could probably adapter their Nitrokey Pro hardware / MCU design into a Framework adapter (link also below). Their hardware supports OpenPGP which is probably what you want to use for storing keys. I currently use a Yubikey and if the support is similar you'd totally be able to store SSH keys, encryption keys, signing keys, etc.

https://github.com/Nitrokey/nitrokey-pro-hardware
https://github.com/Nitrokey/nitrokey-pro-firmware

**Comment by eclecticc** [comment]
The community is a good place to discuss ideas for Expansion Cards: https://community.frame.work/c/developer-program/expansion-card/90

**Comment by CorruptComputer** [comment]
Ah apologies, I didn't know that was where suggestions should go. 

Just checked there and it looks like some folks have already made 3d-printable enclosures for Yubikeys, this is fantastic news for me. Thank you!

For reference in case anyone else is interested: https://community.frame.work/t/yubikey-5c-adapter/23157
