### ISSUE TITLE
Request: Add PDF plots of schematics to the Electrical projects

### ISSUE THREAD

**Issue by DeflateAwning** [FrameworkComputer/ExpansionCards#8]
It would be easier to preview what these projects are without cloning them if you put the plotted PDFs in the repo

**Comment by eclecticc** [comment]
The Microcontroller has a pdf https://github.com/FrameworkComputer/ExpansionCards/blob/main/Electrical/Microcontroller/Microcontroller.pdf

The templates don't because the cards are blank.  They are really just mechanical outlines to avoid needing to draw the geometry yourself.

**Comment by DeflateAwning** [comment]
Thank you

**Comment by eclecticc** [comment]
Added PDFs for the others as well to make that clearer.

**Comment by DeflateAwning** [comment]
Thanks! 

(in commit: https://github.com/FrameworkComputer/ExpansionCards/commit/ee260d97721e38d13001eb6d065263db58813266)
