### ISSUE TITLE
3D Models for Printing Expansion Cards are backward.

### ISSUE THREAD

**Issue by tekchip** [FrameworkComputer/ExpansionCards#9]
The 3D models at https://github.com/FrameworkComputer/ExpansionCards/tree/main/Mechanical are backward. The latch hooks should face back, opposite of the wall with the plug hole, and the lip to get leverage for removal is also at the same end as everything else.

I discovered this after getting a 3D print without modifying any files, just sending it off.

![Framework expansion card tray backward diagram](https://github.com/FrameworkComputer/ExpansionCards/assets/12612055/9589abee-838a-47ad-b472-e099ebcf5662)

![framework expansion cards side by side 1](https://github.com/FrameworkComputer/ExpansionCards/assets/12612055/12469366-455b-4c9d-8601-e2034955f9f5)

![framework expansion cards side by side 2](https://github.com/FrameworkComputer/ExpansionCards/assets/12612055/90271799-13b5-4e8d-8fea-c4e29e73ce87)

![framework expansion card inserted wrong way](https://github.com/FrameworkComputer/ExpansionCards/assets/12612055/04932628-9169-4c15-b773-2eddd08c199a)

**Comment by eclecticc** [comment]
Not sure if I am following your description, but the 3D file looks correct.  The latches are on the same side as the USB-C plug.  The open end is open to give you flexibility to put what you would like there.

**Comment by tekchip** [comment]
> Not sure if I am following your description, but the 3D file looks correct.  The latches are on the same side as the USB-C plug.  The open end is open to give you flexibility to put what you would like there.

For real? I drew a diagram. Look at my photos of the part I had printed next to an actual expansion card.

The closed side with a port hole should face out from the laptop body. The latch clip and external groove to grip the card for removal should be at the opposite end.

In the 3d model all those things are on the same side. That's not how it's supposed to work.

**Comment by eclecticc** [comment]
No, the closed side with the hole is the side that gets inserted into the laptop.  The hole is for the USB-C plug to go through to plug into the Mainboard.  You can see that a regular mass production Expansion Card works the same way.

**Comment by tekchip** [comment]
Apologies, I see what you're saying now. That side is intended to be the internal C connection. The other is to be modified for whatever. 

Perhaps a different issue needs to be addressed then. It's possible I missed it but it was not clear to me, a DIYer, that that was the intended orientation of the tray and that a part is intentionally absent.

Perhaps there's a way to label the image examples or something so it's visually clear which direction relative to the laptop the model is oriented? Haven't spent much time thinking on it having just realized what's going on there.
